config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :airports

  root "flights#index"
  get "/flights", to: "flight#index"
  get "/newnewbooking", to: "bookings#new"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/airport.rb
class Airport < ApplicationRecord

   has_many :departures, class_name: "Flight", foreign_key: "start_id"
   has_many :arrivals, class_name: "Flight", foreign_key: "finish_id"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger

  
end

app/models/flight.rb
class Flight < ApplicationRecord

    belongs_to :from_airport, class_name: "Airport", foreign_key: "start_id"
    belongs_to :to_airport, class_name: "Airport", foreign_key: "finish_id"



   

end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @flight = Flight.find(@booking.flight_id)
  end

  # GET /bookings/new 
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    puts "fliiiiiiiiiiiiiiiiiiiiiiiiiiiightidddddddddddddddddddddddd"
    puts @flight.id
    @passenger = Passenger.new
  end
  
  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    puts "creaaaaaaaaaaaaaaaaaaating paaaaaaaaaaaaaaaaassenger before"

    @passenger = Passenger.create(name: booking_params[:passengers][:name], email: booking_params[:passengers][:email])
    # @passenger = Passenger.create(name: "fakename", email: "fakeemail")


    puts "creaaaaaaaaaaaaaaaaaaating paaaaaaaaaaaaaaaaassenger after"

    @booking = Booking.new(flight_id: booking_params[:flight_id], passenger_id: @passenger.id)
    @flight = Flight.find(booking_params[:flight_id])

    puts "booooooooking naaaaaaaaaaaaaaaaaaaaaaaaaame"
    puts @passenger.name
    puts "booooooooking emaaaaaaaaaaaaaaaaaaaaaaaaaaaaaail"
    puts @passenger.email
    respond_to do |format|
      if @booking.save
        # BookingMailer.with(booking: @booking).thankyou_email.deliver_now
        PassengerMailer.with(passenger: @passenger).thankyou_email.deliver_now

        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:flight_id, passengers: [:name, :email])

    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

    def index

        
        
        if params[:search]
            
            @booking = Booking.new
            
            @flights_dates = @flights_froms = @flights_tos = Flight.all
            
            if params[:search][:date] != ""
                @flights_dates = Flight.all.where(begin_datetime: "#{params[:search][:date]}")
            end
            
            if params[:search][:from] != ""
                @from_airport = Airport.find_by(code: params[:search][:from])
                @flights_froms = Flight.all.where(start_id: @from_airport)
            end
            
            if params[:search][:to] != ""
                @to_airport = Airport.find_by(code: params[:search][:to])
                @flights_tos = Flight.all.where(finish_id: @to_airport)
            end
            
            
            
            # puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@flights_dates_count"
            # puts @flights_dates.count
            
            # puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@flights_froms_count"
            # puts @flights_froms.count
            
            @flights = @flights_dates & @flights_froms & @flights_tos
            
            
            
            # if params[:search][:date] != ""
            #     @flights = Flight.all.where(start_id: "#{@from_airport.id}", finish_id: "#{@to_airport.id}", begin_datetime: "#{params[:search][:date]}")
            # else
            #     @flights = Flight.all.where(start_id: "#{@from_airport.id}", finish_id: "#{@to_airport.id}")
            # end


            
        else
            
            @flights = Flight.all
            
        end
        
        
        
        
        # @arrival = Airport.where(code: params[:search])
        # puts "paraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaams"
        # puts params[:search][:search_departures]

        
        # if params[:search][:search_departures]
        #     puts "searching deparrrrrrrrrrrrrrrrrrrrrrrrrrtures"
        #     @flights = Flight.search(params[:search][:search_departures],"d")
        # else
        #     puts "searching arrrrrrrrrrrrrrrrrrrrrrrrrrrrrivals"
        #     @flights = Flight.search(params[:search][:search_departures],"a")
        # end
    end

    def new
        @flight = Flight.new
    end


end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    puts "creaaaaaaaaaaaaaaaaaaating paaaaaaaaaaaaaaaaassenger"
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        puts "passenger saaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaviiiiiiiiiiiiing name"
        puts @passenger.name
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        puts "passenger not saaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaviiiiiiiiiiiiing"

        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_form.html.erb
<table>
    <thead>
      <tr>
        <th style="width:50px">ID</th>
        <th style="width:250px">Depart</th>
        <th style="width:100px">Duration</th>
        <th style="width:100px">From</th>
        <th style="width:100px">To</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td style="text-align:center"><%= @flight.id %></td>
          <td style="text-align:center"><%= @flight.begin_datetime %></td>
          <td style="text-align:center"><%= @flight.duration %> hours</td>
          <td style="text-align:center"><%= @flight.from_airport.code %></td>
          <td style="text-align:center"><%= @flight.to_airport.code %></td>
        </tr>

    </tbody>
  </table>


<%= simple_form_for @booking, method: "POST" do |f| %>

      <%= f.input :flight_id, as: "hidden", input_html: { value: @flight.id } %>
      
        <%= f.simple_fields_for :passengers do |p| %>
          <%= p.input :name %>
          <%= p.input :email %>
        <% end %>








<% if false %>



      <%= f.fields_for @passenger do |passenger_form|%>

        <%= passenger_form.input :name %>

      <% end %>
<% end %>



<% if false %>
<% end %>

      <%= f.submit "Book" %>
<% end %>






















<% if false %>

<form action = "bookings", method = "POST">
  
<br><br>
  <label for="fname">First name:</label><br>
  <input type="text" id="fname" name="fname"><br><br>
  <label for="lname">Last name:</label><br>
  <input type="text" id="fname" name="lname"><br><br>
  <input type="submit" value="Book Flight"><br>


  <input type="hidden" name="flight_id" value=<%= @flight.id%>><br>

</form>




<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :flight %>
    <%= f.association :passenger %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Passenger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.flight_id %></td>
        <td><%= booking.passenger_id %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<% link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<table>
    <thead>
      <tr>
        <th style="width:50px">ID</th>
        <th style="width:250px">Depart</th>
        <th style="width:100px">Duration</th>
        <th style="width:100px">From</th>
        <th style="width:100px">To</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td style="text-align:center"><%= @flight.id %></td>
          <td style="text-align:center"><%= @flight.begin_datetime %></td>
          <td style="text-align:center"><%= @flight.duration %> hours</td>
          <td style="text-align:center"><%= @flight.from_airport.code %></td>
          <td style="text-align:center"><%= @flight.to_airport.code %></td>
        </tr>

    </tbody>
  </table>

<p>
  <strong>Passenger:</strong>
  <%= Passenger.find(@booking.passenger_id).name %>
</p>

<p>
  <strong>Email:</strong>
  <%= Passenger.find(@booking.passenger_id).email %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>


<% @codes = Airport.all.map {|a| a.code} %>
<% @dates = Flight.all.map {|f| f.begin_datetime}%>
<%= puts "cccccoooooooooooooooodddddddeeeeeesssssss" %>
<%= puts @codes %>

<br><br>

<%= simple_form_for :search, url: root_path, method: "GET" do |f| %>
  <%= f.input :from, collection: @codes %>
  <%= f.input :to, collection: @codes %>
  <%= f.input :number, collection: 1..4 %>
  <%= f.input :date, collection: @dates %>

<br>
  <%= f.submit "Search" %>
<% end %>



<% @flight_listings = @flights.map{|f| " #{f.id}" "#{f.from_airport.code} #{f.to_airport.code} #{f.begin_datetime} #{f.duration}"} %>


<% if false %>
  <%= simple_form_for @booking, url: new_booking_path, method: "GET" do |f| %>


      <%= f.input :flight_id, input_html: { type: 'radio' }, collection: @flight_listings %>
      <%= f.submit "Search" %>
  <% end %>
<% end %>

<br><br>
<form action = "newnewbooking", method = "GET">
  <table>
    <thead>
      <tr>
        <th style="width:50px">ID</th>
        <th style="width:250px">Depart</th>
        <th style="width:100px">Duration</th>
        <th style="width:100px">From</th>
        <th style="width:100px">To</th>
      </tr>
    </thead>

    <tbody>
      <% @flights.each do |flight| %>
        <tr>

          <td>
            <div class="radio">
              <label><input type="radio" name="flight_id" value="<%= flight.id %>" ><%= flight.id %></label>
            </div>
          </td>

          <td style="text-align:center"><%= flight.begin_datetime %></td>
          <td style="text-align:center"><%= flight.duration %> hours</td>
          <td style="text-align:center"><%= flight.from_airport.code %></td>
          <td style="text-align:center"><%= flight.to_airport.code %></td>
        </tr>

        
      <% end %>
    <tr><td><input type="submit" value="Book Flight"></td></tr>
    </tbody>
  </table>
  <input type="hidden" name="passenger_number" value="42" >
</form>

app/views/flights/new.html.erb
<% if false %>
    <%= form_for flight do |f| %>
    <% if flight.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

        <ul>
            <% flight.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <div class="field">
        <%= f.label :flightname %><br />
        <%= f.text_field :flightname, class: "form-control" %>
    </div>
    <div class="action">
        <%= f.submit %>
    </div>
<% end %>




<% end %>


<%= form_with(url: '/flights', method: 'post', local: true) do %>
  <%= text_field_tag(:create_flight) %>
  <br>
  <%= submit_tag("Create Flight") %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_form.html.erb
<%= simple_form_for(@passenger) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.email %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @passenger.email %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>